### PR TITLE
Dont use full paths to gtk dlls on linux

### PR DESCRIPTION
**Pull request by emarcotte**
To address https://github.com/Mono-Game/MonoGame.Dependencies/issues/39.

Not sure what kind of testing is required, I was able to run the pipeline tool successfully after this change and not prior.

### CODE REVIEW

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 - This seem right to you guys?

Also going to wait till after 3.3 is released to merge this.

**Comment by cra0zy** [comment]
This will not work on Ubuntu, this was the first thing I tried when I was setting up config files. I've excluded these files and the dlls from linux installer in https://github.com/mono/MonoGame/pull/3426

If someone could modify Protobuild stuff to not copy gtk and other dll files to the output folder, that would be the best fix.

**Comment by tomspilman** [comment]
> I've excluded these files and the dlls from linux installer

Will that fix https://github.com/Mono-Game/MonoGame.Dependencies/issues/39 ?

**Comment by cra0zy** [comment]
It does fix #39 if people are installing monogame pipeline using the installer. The thing that is not fixed is if the person with non Ubunut linux distro tries to compile from source and just runs the Pipeline. He will either have to delete those few dll files or modify config files.

**Comment by tomspilman** [comment]
> It does fix #39 if people are installing monogame pipeline using the installer

On all Linux distros including Ubuntu then?

> The thing that is not fixed is if the person with non Ubunut linux distro tries to compile from source and just runs the Pipeline

So this is Ubuntu specific if working from source code?

**Comment by cra0zy** [comment]
> On all Linux distros including Ubuntu then?

Yes

Here are all the possible ways this issue can be fixed:
<ul>
<li>Use system gtk libraries when compiling instead of the local ones, change in PipelineReferences.definition. The problem with this is that the build server doesn't have gtk installed. There is gtk for .net here: http://www.monodevelop.com/download/</li>
<li>Disable local copies of gtk libraries in PipelineReferences.definition From what I read I could not find the command for Protobuild.exe that does that.</li>
</ul>

**Comment by tomspilman** [comment]
Gonna close this...  the work @cra0zy is doing will resolve this.

**Pull request closed without merging**
