### PR TITLE
added linux gtk native libs

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by tomspilman** [comment]
I'll merge this soon...  waiting for 3.3 first.

**Comment by tomspilman** [comment]
This still good to merge?

**Comment by cra0zy** [comment]
It's good

**Comment by cra0zy** [comment]
@tomspilman Can you merge this and #46 ?

**Comment by tomspilman** [comment]
Done!

**Comment by cra0zy** [comment]
Thanks!

**Pull request merged**
