### PR TITLE
Added Gtk3 libs

### PR DESCRIPTION
**Pull request by cra0zy**
I'm only adding Gtk3 libs, I am not removing Gtk2 ones. I will modify the Pipeline Tool code so it can compile for both Gtk2 and Gtk3, and maintain both of those until Gtk2 becomes obsolete.

Gtk3 libs are acquired from: https://github.com/mono/gtk-sharp/releases, release 2.99.3, built from source.

### CODE REVIEW

**Comment by KonajuGames** [comment]
What platform are these built for?  Those dll.config files look like they are for Linux only.

**Comment by KonajuGames** [comment]
Or is Linux the only platform we use GTK for the Pipeline tool?

**Comment by cra0zy** [comment]
Gtk2 Pipeline is Mac and Linux
Gtk3 Pipeline will be Linux only

**Comment by cra0zy** [comment]
Here is the difference between Gtk2 and Gtk3(I opened few system apps in background so that you can understand how the pipeline is supposed to look): https://youtu.be/bxf89cZg4Eo

PS. I use dark theme, but Gtk2 doesn't support it so it just reverts to light theme.

**Comment by cra0zy** [comment]
@tomspilman @KonajuGames Can this be merged?

**Comment by KonajuGames** [comment]
I'll merge it now.

**Comment by cra0zy** [comment]
Yey, Thank You

**Pull request merged**
