### PR TITLE
OpenTK Update

### PR DESCRIPTION
**Pull request by cra0zy**
So this contains the newest opentk from github + https://github.com/opentk/opentk/pull/211

### CODE REVIEW

**Comment by tomspilman** [comment]
Gonna wait to merge this until after we push out 3.3.  I'll be back!

**Comment by tomspilman** [comment]
I'm confused here.  I see 3 repos:

https://github.com/opentk/opentk
https://github.com/thefiddler/opentk
https://github.com/andykorth/opentk

Where each seems to be forked from the other.

I believe @thefiddler is the official maintainer of OpenTK and it has been his PRs (https://github.com/Mono-Game/MonoGame.Dependencies/pull/23) we've merged in the past.

Who is @andykorth in relation to OpenTK?

**Comment by cra0zy** [comment]
Read start of @thefiddler reposetory

**Comment by cra0zy** [comment]
Also I think all of them were official at some point, currently https://github.com/andykorth/opentk points to https://github.com/thefiddler/opentk which points to https://github.com/opentk/opentk

**Comment by andykorth** [comment]
I ran a community fork for a while while @thefiddler was away. Use https://github.com/opentk/opentk as the best and most up-to-date fork.

**Comment by tomspilman** [comment]
Thanks for clearing that up @andykorth !

**Comment by cra0zy** [comment]
Thanks for the info!!!!

**Comment by tomspilman** [comment]
Ok... merging!

**Comment by bsclifton** [comment]
Just a heads up for anyone who had the same issue as me (I was beating my head on this over the past week or so)

I was having the game crash on load (specifically during Game.Initialize), giving an error similar to this:
```X Error of failed request:  BadCursor (invalid Cursor parameter)
  Major opcode of failed request:  95 (X_FreeCursor)
  Resource id in failed request:  0x3600005
  Serial number of failed request:  164
  Current serial number in output stream:  166```

The problem was that the Add-In for MonoDevelop installs a nuget package for MonoGame.Framework.Linux, which is stuck at version 3.4.0.459, [which has the bug described here](https://github.com/mono/MonoGame/issues/3540).

I removed the package reference and manually added a reference to /opt/monogame-pipeline/MonoGame.Framework.dll, which worked great :smile:

**Comment by cra0zy** [comment]
> The problem was that the Add-In for MonoDevelop installs a nuget package for MonoGame.Framework.Linux, which is stuck at version 3.4.0.459, which has the bug described here.
> 
> I removed the package reference and manually added a reference to /opt/monogame-pipeline/MonoGame.Framework.dll, which worked great

Yea, the addin isn't automatically using the newest nuget references, but instead always referencing MG 3.4, you can get the develop nuget MonoGame packages from: http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/ just remember to check "Show pre-release packages".

Also if you want to use local references, don't use MG from Pipeline, use: "/usr/lib/mono/xbuild/MonoGame/v3.0/Assemblies".

**Comment by bsclifton** [comment]
Very cool- thanks :+1: (updated reference)

**Pull request merged**
